import { useState } from "react";
import Head from "next/head";
import Gallery from "../components/Gallery";
import Joke from "../components/Joke";
import Matrix from "../components/Matrix";
import Stories from "../components/Stories";
import Tasks from "../components/Tasks";

function HomePage() {
    const [userQuery, setUserQuery] = useState("");
    const [showGallery, setShowGallery] = useState(true);

    const updateUserQuery = (e) => {
        setUserQuery(e.target.value);
    };

    const handleKeyPress = (e) => {
        if (e.key === "Enter") {
            searchQuery();
        }
    };

    const searchQuery = () => {
        window.open(`https://google.co.uk/search?q=${userQuery}`, "_blank");
    };

    const toggleShowGallery = () => {
        setShowGallery((currentState) => !currentState);
    };

    return (
        <div>
            <Head>
                <title>Master React Hooks</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Home</h1>
                <div className="form">
                    <input value={userQuery} onChange={updateUserQuery} onKeyPress={handleKeyPress} />
                    <button onClick={searchQuery}>Search</button>
                </div>

                <hr />
                <Joke />

                <hr />
                <Tasks />

                <hr />
                <div>
                    {showGallery ? <Gallery /> : null}
                    <button onClick={toggleShowGallery}>{showGallery ? "Hide" : "Show"} gallery</button>
                </div>

                <hr />
                <Stories />

                <hr />
                <Matrix />
            </main>
        </div>
    );
}

export default HomePage;
